"""Turn a guilds-channels CSV into a `discovery.guilds[].selectors` YAML snippet.

Companion to ``tools/list_guilds_channels.py``. Workflow::

    1. Run list_guilds_channels.py → guilds_channels.csv
       (columns: guild_name|guild_id|channel_id|channel_name)
    2. Open the CSV in your editor / Excel / vim, add a 5th column `pick`
       with `1` (or `x`, `y`, `yes`, `true`) on every row you want to scan.
       Save back as pipe-delimited.
    3. Run this tool → scope_snippet.yaml
       (a `discovery.guilds: [...]` block ready to paste into config.live.yaml)

If the CSV has no `pick` column at all, every row is included (rare —
useful when you want to scan literally every scannable channel).

The emitted block matches the v2 selector path
(``discovery.GuildSelectorEntry`` + ``selectors.GuildSelectorConfig``):
``selectors.channels`` is a list of fnmatch globs, evaluated against
channel names (case-insensitive) at scan time. We use **channel names**,
not IDs, because the v2 selector path matches by name. If two channels
in the same guild share a name, both will be picked up — usually fine,
but the tool warns if it spots a collision.

Usage::

    python tools/csv_to_scan_scope.py \\
        --input guilds_channels.csv \\
        --output scope_snippet.yaml
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import sys
from collections import defaultdict
from pathlib import Path

_PICK_TRUE = {"1", "x", "y", "yes", "true", "*"}


def _is_picked(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in _PICK_TRUE


def _load_rows(path: Path) -> tuple[list[dict[str, str]], bool]:
    """Return (rows, has_pick_column)."""
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="|")
        try:
            header = next(reader)
        except StopIteration:
            print(f"empty CSV: {path}", file=sys.stderr)
            return [], False
        header_norm = [h.strip().lower() for h in header]
        required = {"guild_name", "guild_id", "channel_id", "channel_name"}
        missing = required - set(header_norm)
        if missing:
            print(
                f"CSV missing required columns: {sorted(missing)}; got {header_norm}",
                file=sys.stderr,
            )
            sys.exit(1)
        has_pick = "pick" in header_norm
        rows: list[dict[str, str]] = []
        for raw in reader:
            if not raw or all(not c.strip() for c in raw):
                continue
            padded = raw + [""] * (len(header_norm) - len(raw))
            rows.append(dict(zip(header_norm, padded, strict=False)))
        return rows, has_pick


def _yaml_quote(s: str) -> str:
    """Conservative double-quoted YAML scalar with backslash + quote escapes.

    The strings we emit are guild/channel names — Unicode is fine, but they
    can contain colons, brackets, leading dashes, emoji modifiers, etc. that
    need quoting. Always quote → simplest correct path.
    """
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render(
    grouped: dict[str, dict[str, object]],
    *,
    src_path: Path,
    total_rows: int,
    picked_rows: int,
) -> str:
    today = _dt.date.today().isoformat()
    lines: list[str] = [
        f"# Generated by tools/csv_to_scan_scope.py on {today}",
        f"# Source: {src_path.name} ({picked_rows}/{total_rows} rows picked)",
        "# Paste under `discovery:` in config.live.yaml. The `manual_invites`",
        "# / `invites_input` fields are unaffected; this only adds per-guild",
        "# selectors. Selectors match channel names via fnmatch (case-insens).",
        "",
        "discovery:",
        "  guilds:",
    ]
    for guild_id in sorted(grouped, key=lambda g: (str(grouped[g]["name"]).casefold(), g)):
        info = grouped[guild_id]
        names: list[str] = sorted({n for n in info["channels"] if n}, key=str.casefold)  # type: ignore[arg-type]
        if not names:
            continue
        lines.append(f"    # {info['name']}")
        lines.append(f"    - id: {_yaml_quote(guild_id)}")
        lines.append("      selectors:")
        lines.append("        channels:")
        for n in names:
            lines.append(f"          - {_yaml_quote(n)}")
    lines.append("")
    return "\n".join(lines)


def _detect_collisions(
    grouped: dict[str, dict[str, object]],
) -> list[tuple[str, str, int]]:
    """Return (guild_name, channel_name, count) where the same channel name
    appears more than once inside one guild. Caller warns the operator.
    """
    collisions: list[tuple[str, str, int]] = []
    for guild_id, info in grouped.items():
        seen: dict[str, int] = defaultdict(int)
        for ch_id, ch_name in info["channel_pairs"]:  # type: ignore[index]
            if ch_name:
                seen[ch_name] += 1
        for n, c in seen.items():
            if c > 1:
                collisions.append((str(info["name"]), n, c))
    return collisions


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", maxsplit=1)[0])
    p.add_argument("--input", required=True, type=Path, help="guilds_channels.csv")
    p.add_argument(
        "--output",
        default=Path("scope_snippet.yaml"),
        type=Path,
        help="YAML snippet output (default: scope_snippet.yaml)",
    )
    args = p.parse_args()

    rows, has_pick = _load_rows(args.input)
    total = len(rows)
    if has_pick:
        picked = [r for r in rows if _is_picked(r.get("pick"))]
        picked_count = len(picked)
        if picked_count == 0:
            print(
                "no rows have pick∈{1,x,y,yes,true,*}; nothing to emit. "
                "Add a `pick` column with `1` on rows you want.",
                file=sys.stderr,
            )
            return 1
    else:
        picked = rows
        picked_count = total
        print(
            "note: CSV has no `pick` column → including ALL rows. "
            "Add a `pick` column to filter.",
            file=sys.stderr,
        )

    grouped: dict[str, dict[str, object]] = {}
    for r in picked:
        gid = r["guild_id"].strip()
        if not gid:
            continue
        if gid not in grouped:
            grouped[gid] = {
                "name": r["guild_name"].strip(),
                "channels": [],
                "channel_pairs": [],
            }
        ch_name = r["channel_name"].strip()
        ch_id = r["channel_id"].strip()
        grouped[gid]["channels"].append(ch_name)  # type: ignore[union-attr]
        grouped[gid]["channel_pairs"].append((ch_id, ch_name))  # type: ignore[union-attr]

    collisions = _detect_collisions(grouped)
    for guild_name, ch_name, c in collisions:
        print(
            f"WARN: {guild_name!r} has {c} channels named {ch_name!r}; "
            "fnmatch will pick all of them. Consider editing the CSV to use "
            "a more specific name or remove duplicates.",
            file=sys.stderr,
        )

    out = _render(
        grouped,
        src_path=args.input,
        total_rows=total,
        picked_rows=picked_count,
    )
    args.output.write_text(out, encoding="utf-8")
    print(
        f"wrote {args.output} — {len(grouped)} guilds, "
        f"{picked_count}/{total} rows."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
